use std::fs;

use tempfile::tempdir;

use crate::{analyze_project, model::DxCheckEngineOptions};

#[test]
fn flags_declarative_project_maintainability_rules() {
    let temp = tempdir().unwrap();
    fs::create_dir_all(temp.path().join("src")).unwrap();
    fs::write(
        temp.path().join("src").join("GiantComponent.tsx"),
        "export function GiantComponent() {\n".repeat(420),
    )
    .unwrap();
    fs::write(temp.path().join("src").join("generated.machine"), "cache").unwrap();
    fs::create_dir_all(temp.path().join("node_modules")).unwrap();

    let report = analyze_project(temp.path(), DxCheckEngineOptions::default()).unwrap();
    let ids = report
        .findings
        .iter()
        .map(|finding| finding.id.as_str())
        .collect::<Vec<_>>();

    assert!(ids.contains(&"source-file-line-count"));
    assert!(ids.contains(&"generated-machine-leak"));
    assert!(ids.contains(&"source-owned-node-modules"));
    assert!(ids.contains(&"giant-component"));
}

#[test]
fn default_rules_ignore_generated_serializer_cache_for_source_size_scoring() {
    let temp = tempdir().unwrap();
    fs::create_dir_all(temp.path().join(".dx").join("serializer")).unwrap();
    fs::create_dir_all(temp.path().join(".dx").join("check")).unwrap();
    fs::create_dir_all(temp.path().join(".dx").join("cli")).unwrap();
    fs::create_dir_all(temp.path().join(".dx").join("www")).unwrap();
    fs::create_dir_all(
        temp.path()
            .join(".dx")
            .join("icon")
            .join("machine")
            .join("v1"),
    )
    .unwrap();
    fs::create_dir_all(
        temp.path()
            .join(".dx")
            .join("media")
            .join("machine")
            .join("v1"),
    )
    .unwrap();
    fs::create_dir_all(temp.path().join(".dx").join("dcp").join("cache")).unwrap();
    fs::create_dir_all(temp.path().join("src")).unwrap();
    fs::write(temp.path().join("README.md"), "# Demo\n").unwrap();
    fs::write(temp.path().join("src").join("lib.rs"), "pub fn ok() {}\n").unwrap();

    write_large_machine(temp.path(), ".dx/serializer/check-launch-report.machine");
    write_large_machine(temp.path(), ".dx/check/check-report-latest.machine");
    write_large_machine(temp.path(), ".dx/cli/status-latest.machine");
    write_large_machine(temp.path(), ".dx/www/forge-package-status.machine");
    write_large_machine(temp.path(), ".dx/www/style-check-receipt.machine");
    write_large_machine(temp.path(), ".dx/icon/machine/v1/catalog.machine");
    write_large_machine(temp.path(), ".dx/media/machine/v1/provider-catalog.machine");
    write_large_machine(temp.path(), ".dx/dcp/cache/schema-registry.machine");
    fs::write(temp.path().join("src").join("generated.machine"), "cache").unwrap();

    let report = analyze_project(temp.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(
        !report.findings.iter().any(|finding| {
            finding
                .file
                .as_deref()
                .is_some_and(|file| file.starts_with(".dx/"))
        }),
        "approved generated machine caches must not create source-owned findings"
    );
    assert!(
        report.findings.iter().any(|finding| {
            finding.id == "generated-machine-leak"
                && finding.file.as_deref() == Some("src/generated.machine")
        }),
        "misplaced machine artifacts outside .dx/serializer should still be flagged"
    );
}

#[test]
fn default_rules_flag_generated_source_leaks() {
    let temp = tempdir().unwrap();
    fs::create_dir_all(temp.path().join("src")).unwrap();
    fs::write(
        temp.path().join("src").join("schema.generated.ts"),
        "export type GeneratedSchema = {};\n",
    )
    .unwrap();
    fs::write(
        temp.path().join("src").join("client.gen.rs"),
        "pub struct GeneratedClient;\n",
    )
    .unwrap();
    fs::write(
        temp.path().join("src").join("manual.ts"),
        "// @generated by a schema compiler\nexport const generated = true;\n",
    )
    .unwrap();
    fs::write(
        temp.path().join("src").join("service.pb.js"),
        "export const protobufClient = true;\n",
    )
    .unwrap();
    fs::write(
        temp.path().join("src").join("editable.ts"),
        "export const handAuthored = true;\n",
    )
    .unwrap();

    let report = analyze_project(temp.path(), DxCheckEngineOptions::default()).unwrap();
    let generated_files = report
        .findings
        .iter()
        .filter(|finding| finding.id == "generated-source-leak")
        .filter_map(|finding| finding.file.as_deref())
        .collect::<Vec<_>>();

    assert!(generated_files.contains(&"src/schema.generated.ts"));
    assert!(generated_files.contains(&"src/client.gen.rs"));
    assert!(generated_files.contains(&"src/manual.ts"));
    assert!(generated_files.contains(&"src/service.pb.js"));
    assert!(
        !generated_files.contains(&"src/editable.ts"),
        "hand-authored source must not be reported as generated"
    );
}

#[test]
fn default_rules_do_not_flag_generated_marker_documentation() {
    let temp = tempdir().unwrap();
    fs::create_dir_all(temp.path().join("docs")).unwrap();
    fs::create_dir_all(temp.path().join("src")).unwrap();
    fs::write(
        temp.path().join("docs").join("generated.md"),
        "# Generated Code Policy\n\nMention @generated and DO NOT EDIT in docs only.\n",
    )
    .unwrap();
    fs::write(
        temp.path().join("docs").join("rule-notes.sr"),
        "note=\"@generated marker examples are documentation\"\n",
    )
    .unwrap();
    fs::write(
        temp.path().join("docs").join("generated.json"),
        "{ \"note\": \"Code generated markers in docs are not source leaks\" }\n",
    )
    .unwrap();
    fs::write(
        temp.path().join("src").join("schema.generated.ts"),
        "export type GeneratedSchema = {};\n",
    )
    .unwrap();

    let report = analyze_project(temp.path(), DxCheckEngineOptions::default()).unwrap();
    let generated_files = report
        .findings
        .iter()
        .filter(|finding| finding.id == "generated-source-leak")
        .filter_map(|finding| finding.file.as_deref())
        .collect::<Vec<_>>();

    assert!(generated_files.contains(&"src/schema.generated.ts"));
    assert!(
        !generated_files.contains(&"docs/generated.md"),
        "documentation that explains generated-code markers must not be scored as generated source"
    );
    assert!(!generated_files.contains(&"docs/rule-notes.sr"));
    assert!(!generated_files.contains(&"docs/generated.json"));
}

#[test]
fn default_rules_flag_unfriendly_file_and_folder_names() {
    let temp = tempdir().unwrap();
    fs::create_dir_all(temp.path().join("src").join("Feature Space")).unwrap();
    fs::write(
        temp.path()
            .join("src")
            .join("Feature Space")
            .join("Bad Component.tsx"),
        "export function BadComponent() { return null; }\n",
    )
    .unwrap();

    let report = analyze_project(temp.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(report.findings.iter().any(|finding| {
        finding.id == "source-owned-naming-convention"
            && finding
                .file
                .as_deref()
                .is_some_and(|file| file.contains("Bad Component.tsx"))
    }));
}

#[test]
fn default_rules_flag_components_with_server_boundary_leaks() {
    let temp = tempdir().unwrap();
    fs::create_dir_all(temp.path().join("src").join("components")).unwrap();
    fs::write(
        temp.path().join("src").join("components").join("Card.tsx"),
        "import fs from 'fs';\nexport function Card() { return <div />; }\n",
    )
    .unwrap();

    let report = analyze_project(temp.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(report.findings.iter().any(|finding| {
        finding.id == "component-boundary-leak"
            && finding.file.as_deref() == Some("src/components/Card.tsx")
            && finding.message.contains("server-only module")
    }));
}

#[test]
fn default_rules_treat_pascal_case_tsx_files_as_component_shaped() {
    let temp = tempdir().unwrap();
    let dir = temp.path().join("src").join("features").join("chat");
    fs::create_dir_all(&dir).unwrap();
    fs::write(
        dir.join("ChatPanel.tsx"),
        format!(
            "import fs from 'fs';\nexport function ChatPanel() {{ return <div />; }}\n{}",
            "const row = 1;\n".repeat(301)
        ),
    )
    .unwrap();

    let report = analyze_project(temp.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(report.findings.iter().any(|finding| {
        finding.id == "giant-component"
            && finding.file.as_deref() == Some("src/features/chat/ChatPanel.tsx")
    }));
    assert!(report.findings.iter().any(|finding| {
        finding.id == "component-boundary-leak"
            && finding.file.as_deref() == Some("src/features/chat/ChatPanel.tsx")
    }));
}

#[test]
fn default_rules_flag_component_quality_gaps_without_requiring_shadcn() {
    let temp = tempdir().unwrap();
    fs::create_dir_all(temp.path().join("src").join("components")).unwrap();
    fs::write(
        temp.path().join("src").join("components").join("Badge.tsx"),
        "export function Badge() { return <span>New</span>; }\n",
    )
    .unwrap();

    let report = analyze_project(temp.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(report.findings.iter().any(|finding| {
        finding.id == "component-quality-affordance"
            && finding.file.as_deref() == Some("src/components/Badge.tsx")
            && finding.message.contains("className")
    }));
}

fn write_large_machine(root: &std::path::Path, relative_path: &str) {
    fs::write(root.join(relative_path), "x".repeat(130_000)).unwrap();
}
