use std::fs;

use dx_check_engine::{DxCheckEngineOptions, analyze_project};
use tempfile::tempdir;

#[test]
fn default_rules_ignore_generated_marker_strings_inside_detection_code() {
    let root = tempdir().unwrap();
    fs::create_dir_all(root.path().join("src")).unwrap();
    fs::write(root.path().join("README.md"), "# Demo\n").unwrap();
    fs::write(
        root.path().join("src").join("lib.rs"),
        r#"
pub fn marker_terms() -> [&'static str; 3] {
    ["@generated", "do not edit", "code generated"]
}
"#,
    )
    .unwrap();

    let report = analyze_project(root.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(
        !report.findings.iter().any(|finding| {
            finding.id == "generated-source-leak" && finding.file.as_deref() == Some("src/lib.rs")
        }),
        "literal detection terms inside hand-authored code should not look generated"
    );
}

#[test]
fn default_rules_still_flag_generated_marker_in_source_header() {
    let root = tempdir().unwrap();
    fs::create_dir_all(root.path().join("src")).unwrap();
    fs::write(root.path().join("README.md"), "# Demo\n").unwrap();
    fs::write(
        root.path().join("src").join("client.ts"),
        "// Code generated by schema compiler. DO NOT EDIT.\nexport const client = true;\n",
    )
    .unwrap();

    let report = analyze_project(root.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(report.findings.iter().any(|finding| {
        finding.id == "generated-source-leak" && finding.file.as_deref() == Some("src/client.ts")
    }));
}

#[test]
fn default_rules_ignore_rust_unwraps_in_test_files() {
    let root = tempdir().unwrap();
    fs::create_dir_all(root.path().join("src")).unwrap();
    fs::create_dir_all(root.path().join("tests")).unwrap();
    fs::write(root.path().join("README.md"), "# Demo\n").unwrap();
    fs::write(root.path().join("src").join("lib.rs"), "pub fn ok() {}\n").unwrap();
    fs::write(
        root.path().join("tests").join("smoke.rs"),
        "use tempfile::tempdir;\n#[test]\nfn smoke() { let _root = tempdir().unwrap(); }\n",
    )
    .unwrap();

    let report = analyze_project(root.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(
        !report.findings.iter().any(|finding| {
            finding.id == "rust-unwrap-maintainability"
                && finding.file.as_deref() == Some("tests/smoke.rs")
        }),
        "test helper unwraps should not be treated as application-path unwraps"
    );
}

#[test]
fn default_rules_still_flag_rust_unwraps_in_production_source() {
    let root = tempdir().unwrap();
    fs::create_dir_all(root.path().join("src")).unwrap();
    fs::write(root.path().join("README.md"), "# Demo\n").unwrap();
    fs::write(
        root.path().join("src").join("lib.rs"),
        "pub fn parse_port(value: &str) -> u16 { value.parse::<u16>().unwrap() }\n",
    )
    .unwrap();

    let report = analyze_project(root.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(report.findings.iter().any(|finding| {
        finding.id == "rust-unwrap-maintainability" && finding.file.as_deref() == Some("src/lib.rs")
    }));
}

#[test]
fn default_rules_ignore_insecure_default_strings_inside_detection_code() {
    let root = tempdir().unwrap();
    fs::create_dir_all(root.path().join("src")).unwrap();
    fs::write(root.path().join("README.md"), "# Demo\n").unwrap();
    fs::write(
        root.path().join("src").join("lib.rs"),
        r#"
pub fn insecure_terms() -> [&'static str; 4] {
    ["password = \"", "secret = \"", "api_key = \"", "dangerouslySetInnerHTML"]
}
"#,
    )
    .unwrap();

    let report = analyze_project(root.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(
        !report.findings.iter().any(|finding| {
            finding.id == "insecure-source-defaults"
                && finding.file.as_deref() == Some("src/lib.rs")
        }),
        "literal detection terms should not count as insecure defaults"
    );
}

#[test]
fn default_rules_still_flag_hard_coded_secret_defaults() {
    let root = tempdir().unwrap();
    fs::create_dir_all(root.path().join("src")).unwrap();
    fs::write(root.path().join("README.md"), "# Demo\n").unwrap();
    fs::write(
        root.path().join("src").join("config.ts"),
        "export const password = \"demo\";\n",
    )
    .unwrap();

    let report = analyze_project(root.path(), DxCheckEngineOptions::default()).unwrap();

    assert!(report.findings.iter().any(|finding| {
        finding.id == "insecure-source-defaults" && finding.file.as_deref() == Some("src/config.ts")
    }));
}
