use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

use serde_json::json;
use tempfile::tempdir;

use dx_check_engine::adapters::plan_tools;
use dx_check_engine::diagnostics::{parse_cargo_json_lines, parse_tool_output};
use dx_check_engine::model::{DxMeasurementKind, DxSeverity, DxToolPlan, DxToolTarget};

fn plan(id: &str, parser: &str, target: DxToolTarget) -> DxToolPlan {
    DxToolPlan {
        id: id.to_string(),
        target,
        executable: "tool".to_string(),
        args: Vec::new(),
        cwd: PathBuf::from("G:\\demo"),
        detected_from: vec!["fixture".to_string()],
        parser: parser.to_string(),
    }
}

#[test]
fn every_planned_parser_has_explicit_test_coverage() {
    let root = tempdir().unwrap();
    fs::write(
        root.path().join("Cargo.toml"),
        "[package]\nname='demo'\nversion='0.1.0'\nedition='2024'\n",
    )
    .unwrap();
    fs::write(
        root.path().join("package.json"),
        r#"{
  "scripts": {
"lint": "eslint .",
"format:check": "prettier --check .",
"typecheck": "tsc --noEmit",
"test": "vitest run"
  },
  "devDependencies": {
"@biomejs/biome": "^2.4.16"
  }
}
"#,
    )
    .unwrap();
    fs::write(root.path().join("pyproject.toml"), "[tool.ruff]\n").unwrap();
    fs::write(root.path().join("go.mod"), "module demo\n").unwrap();
    fs::write(
        root.path().join("dx"),
        r#"
biome[target path enabled](
lint . true
format . true
)

web_audit_targets[id url required_status max_html_bytes](
home "http://localhost:3000/" 200 200000
)
"#,
    )
    .unwrap();
    fs::create_dir_all(root.path().join("src")).unwrap();
    fs::create_dir_all(root.path().join("build").join("debug")).unwrap();
    fs::write(
        root.path().join("src").join("main.cpp"),
        "int main() { return 0; }\n",
    )
    .unwrap();
    fs::write(root.path().join(".clang-format"), "BasedOnStyle: LLVM\n").unwrap();
    fs::write(root.path().join(".clang-tidy"), "Checks: bugprone-*\n").unwrap();
    fs::write(
        root.path().join("compile_commands.json"),
        r#"[
  { "directory": ".", "command": "clang++ -c src/main.cpp", "file": "src/main.cpp" }
]
"#,
    )
    .unwrap();
    fs::write(
        root.path().join("CMakeLists.txt"),
        "cmake_minimum_required(VERSION 3.25)\nproject(demo CXX)\n",
    )
    .unwrap();
    fs::write(
        root.path()
            .join("build")
            .join("debug")
            .join("CMakeCache.txt"),
        format!(
            "# configured CMake build directory\nCMAKE_HOME_DIRECTORY:INTERNAL={}\n",
            root.path().display()
        ),
    )
    .unwrap();
    fs::write(
        root.path()
            .join("build")
            .join("debug")
            .join("CTestTestfile.cmake"),
        format!(
            "# generated by CTest\n# Source directory: {}\n",
            root.path().display()
        ),
    )
    .unwrap();

    let planned = plan_tools(
        root.path(),
        &[
            DxToolTarget::Lint,
            DxToolTarget::Format,
            DxToolTarget::Typecheck,
            DxToolTarget::Test,
            DxToolTarget::Audit,
        ],
    )
    .into_iter()
    .map(|plan| plan.parser)
    .chain({
        let black_root = tempdir().unwrap();
        fs::write(
            black_root.path().join("pyproject.toml"),
            "[tool.black]\nline-length = 100\n",
        )
        .unwrap();
        plan_tools(black_root.path(), &[DxToolTarget::Format])
            .into_iter()
            .map(|plan| plan.parser)
            .collect::<Vec<_>>()
    })
    .collect::<BTreeSet<_>>();
    let covered = [
        "black",
        "biome-json",
        "cargo-json",
        "clang-format",
        "clangd",
        "clang-tidy",
        "cppcheck-xml",
        "ctest",
        "cxx-compiler",
        "gofmt-list",
        "go-test",
        "go-vet",
        "package-script",
        "pytest",
        "ruff-format",
        "ruff-json",
        "rustfmt",
        "web-audit-json",
    ]
    .into_iter()
    .map(ToOwned::to_owned)
    .collect::<BTreeSet<_>>();

    assert_eq!(planned, covered);
}

#[test]
fn parses_web_audit_json_diagnostics() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "schema_version": "dx.web_audit.result.v1",
  "id": "home-run",
  "target_id": "home",
  "url": "http://localhost:3000/",
  "status": 503,
  "html_bytes": 250000,
  "title_present": false,
  "description_present": true,
  "security_header_count": 1,
  "diagnostics": [
    {
      "id": "web-http-status",
      "severity": "failure",
      "message": "HTTP status was 503",
      "next_action": "Fix the preview response."
    }
  ]
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:web-http-status");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert_eq!(
        diagnostics[0].file.as_deref(),
        Some("http://localhost:3000/")
    );
    assert_eq!(diagnostics[0].message, "HTTP status was 503");
    assert_eq!(diagnostics[0].next_action, "Fix the preview response.");
}

#[test]
fn parses_web_lighthouse_audit_diagnostics() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "schema_version": "dx.check.web_audit.v1",
  "id": "home-run",
  "target_id": "home",
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "schema_version": "dx.check.web_lighthouse",
    "id": "home-lighthouse",
    "target_id": "home",
    "url": "http://localhost:3000/",
    "score": 300,
    "max_score": 400,
    "categories": [],
    "audits": [
      {
        "id": "accessibility-image-alt",
        "category": "accessibility",
        "label": "Image alt text",
        "score": 0,
        "max_score": 100,
        "status": "warning",
        "detail": "1 captured element needs attention.",
        "next_action": "Add alt text."
      },
      {
        "id": "seo-title",
        "category": "seo",
        "label": "Document title",
        "score": 100,
        "max_score": 100,
        "status": "ready",
        "detail": "Title exists.",
        "next_action": "Keep it descriptive."
      }
    ]
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:accessibility-image-alt");
    assert_eq!(diagnostics[0].severity, DxSeverity::Warning);
    assert_eq!(
        diagnostics[0].file.as_deref(),
        Some("http://localhost:3000/")
    );
    assert_eq!(
        diagnostics[0].message,
        "Image alt text: 1 captured element needs attention."
    );
    assert_eq!(diagnostics[0].next_action, "Add alt text.");
}

#[test]
fn web_lighthouse_parser_ignores_ready_audits() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "schema_version": "dx.check.web_audit.v1",
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "audits": [
      {
        "id": "seo-title",
        "label": "Document title",
        "score": 100,
        "max_score": 100,
        "status": "ready",
        "detail": "Title exists.",
        "next_action": "Keep it descriptive."
      }
    ]
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert!(diagnostics.is_empty());
}

#[test]
fn ready_web_lighthouse_audit_with_low_score_is_invalid_runner_output() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "schema_version": "dx.check.web_audit.v1",
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "audits": [
      {
        "id": "performance-http-status",
        "label": "HTTP status",
        "score": 0,
        "max_score": 100,
        "status": "ready",
        "detail": "Returned HTTP 500",
        "next_action": "Fix failing routes."
      }
    ]
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("ready"));
    assert!(diagnostics[0].message.contains("score"));
}

#[test]
fn web_lighthouse_aggregate_score_mismatch_with_all_ready_audits_is_invalid_runner_output() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "schema_version": "dx.check.web_audit.v1",
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "score": 300,
    "max_score": 400,
    "audits": [
      {
        "id": "seo-title",
        "label": "Document title",
        "score": 100,
        "max_score": 100,
        "status": "ready",
        "detail": "Title exists.",
        "next_action": "Keep it descriptive."
      }
    ]
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("Lighthouse"));
    assert!(diagnostics[0].message.contains("score"));
}

#[test]
fn parses_blocked_web_lighthouse_audits_as_failure_diagnostics() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "schema_version": "dx.check.web_audit.v1",
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "audits": [
      {
        "id": "performance-http-status",
        "label": "HTTP status",
        "status": "blocked",
        "detail": "Returned HTTP 503",
        "next_action": "Fix the route."
      }
    ]
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:performance-http-status");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
}

#[test]
fn web_audit_parser_reports_failure_diagnostics_hidden_by_display_cap() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let mut audit_diagnostics = (0..32)
        .map(|index| {
            json!({
                "id": format!("web-info-{index}"),
                "severity": "info",
                "message": format!("Informational web audit detail {index}"),
                "next_action": "Keep monitoring this signal."
            })
        })
        .collect::<Vec<_>>();
    audit_diagnostics.push(json!({
        "id": "web-hidden-failure",
        "severity": "failure",
        "message": "A failure appeared after the display cap.",
        "next_action": "Fix the hidden failure."
    }));
    let stdout = serde_json::to_vec(&json!({
        "schema_version": "dx.check.web_audit.v1",
        "url": "http://localhost:3000/",
        "diagnostics": audit_diagnostics
    }))
    .expect("web audit json");

    let diagnostics = parse_tool_output(&plan, &stdout, b"");

    assert!(
        diagnostics.iter().any(|diagnostic| {
            diagnostic.id == "web-audit-home:web-hidden-failure"
                && diagnostic.severity == DxSeverity::Failure
        }),
        "hidden failure must still block the score: {diagnostics:#?}"
    );
}

#[test]
fn web_lighthouse_parser_reports_non_ready_audits_hidden_by_display_cap() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let mut audits = (0..32)
        .map(|index| {
            json!({
                "id": format!("seo-ready-{index}"),
                "label": format!("Ready audit {index}"),
                "score": 100,
                "max_score": 100,
                "status": "ready",
                "detail": "This audit passed.",
                "next_action": "Keep this passing."
            })
        })
        .collect::<Vec<_>>();
    audits.push(json!({
        "id": "performance-hidden-blocked",
        "label": "Performance score",
        "status": "blocked",
        "detail": "Official Lighthouse could not complete scoring.",
        "next_action": "Inspect the official Lighthouse artifact."
    }));
    let stdout = serde_json::to_vec(&json!({
        "schema_version": "dx.check.web_audit.v1",
        "url": "http://localhost:3000/",
        "diagnostics": [],
        "lighthouse": {
            "schema_version": "dx.check.web_lighthouse",
            "audits": audits
        }
    }))
    .expect("web audit json");

    let diagnostics = parse_tool_output(&plan, &stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(
        diagnostics[0].id,
        "web-audit-home:performance-hidden-blocked"
    );
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
}

#[test]
fn malformed_web_lighthouse_report_emits_invalid_runner_output_diagnostic() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "schema_version": "dx.check.web_audit.v1",
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "schema_version": "dx.check.web_lighthouse",
    "audits": {
      "seo-title": { "status": "ready" }
    }
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("lighthouse.audits"));
}

#[test]
fn invalid_web_audit_json_emits_invalid_runner_output_diagnostic() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);

    let diagnostics = parse_tool_output(&plan, b"not json", b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("web audit JSON"));
}

#[test]
fn empty_web_audit_output_is_invalid_runner_output() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);

    let diagnostics = parse_tool_output(&plan, b"", b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("empty"));
    assert!(diagnostics[0].message.contains("web audit JSON"));
}

#[test]
fn web_audit_json_without_diagnostics_or_lighthouse_is_invalid_runner_output() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);

    let diagnostics = parse_tool_output(&plan, br#"{"url":"http://localhost:3000/"}"#, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("diagnostics"));
    assert!(diagnostics[0].message.contains("lighthouse"));
}

#[test]
fn web_audit_json_with_empty_evidence_is_invalid_runner_output() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let cases = [
        br#"{"url":"http://localhost:3000/","diagnostics":[]}"#.as_slice(),
        br#"{"url":"http://localhost:3000/","diagnostics":[],"lighthouse":{"audits":[]}}"#
            .as_slice(),
    ];

    for stdout in cases {
        let diagnostics = parse_tool_output(&plan, stdout, b"");

        assert_eq!(diagnostics.len(), 1, "stdout: {:?}", stdout);
        assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
        assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
        assert!(
            diagnostics[0].message.contains("empty evidence"),
            "message: {}",
            diagnostics[0].message
        );
    }
}

#[test]
fn web_audit_json_with_unknown_status_and_no_diagnostics_is_invalid_runner_output() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let cases = [
        br#"{"url":"http://localhost:3000/","status":null,"diagnostics":[]}"#.as_slice(),
        br#"{"url":"http://localhost:3000/","status":"unknown","diagnostics":[]}"#.as_slice(),
        br#"{"url":"http://localhost:3000/","status":0,"diagnostics":[]}"#.as_slice(),
        br#"{"url":"http://localhost:3000/","status":600,"diagnostics":[]}"#.as_slice(),
    ];

    for stdout in cases {
        let diagnostics = parse_tool_output(&plan, stdout, b"");

        assert_eq!(diagnostics.len(), 1, "stdout: {:?}", stdout);
        assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
        assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
        assert!(
            diagnostics[0].message.contains("status"),
            "message: {}",
            diagnostics[0].message
        );
    }
}

#[test]
fn web_audit_json_rejects_unknown_diagnostic_severity() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "url": "http://localhost:3000/",
  "diagnostics": [
    {
      "id": "web-http-status",
      "severity": "fatal",
      "message": "HTTP probe crashed",
      "next_action": "Inspect the web audit runner."
    }
  ]
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("severity"));
}

#[test]
fn web_audit_json_rejects_non_string_diagnostic_severity() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "url": "http://localhost:3000/",
  "diagnostics": [
    {
      "id": "web-http-status",
      "severity": 7,
      "message": "HTTP probe crashed",
      "next_action": "Inspect the web audit runner."
    }
  ]
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("severity"));
}

#[test]
fn web_audit_json_rejects_invalid_status_even_with_diagnostics() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "url": "http://localhost:3000/",
  "status": "unknown",
  "diagnostics": [
    {
      "id": "web-title",
      "severity": "warning",
      "message": "Title is missing",
      "next_action": "Add a page title."
    }
  ]
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("status"));
}

#[test]
fn web_lighthouse_json_rejects_unknown_audit_status() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "audits": [
      {
        "id": "performance-http-status",
        "label": "HTTP status",
        "status": "fatal",
        "detail": "The runner crashed before scoring.",
        "next_action": "Inspect the web audit runner."
      }
    ]
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("status"));
}

#[test]
fn web_lighthouse_json_rejects_warning_audit_with_max_score() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "audits": [
      {
        "id": "performance-http-status",
        "label": "HTTP status",
        "score": 100,
        "max_score": 100,
        "status": "warning",
        "detail": "Status is warning despite a perfect score.",
        "next_action": "Regenerate the Lighthouse evidence."
      }
    ]
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("score"));
}

#[test]
fn parses_cargo_compiler_message_into_typed_diagnostic() {
    let output = r#"{"reason":"compiler-artifact","package_id":"demo 0.1.0 (path+file:///demo)"}"#
        .to_string()
        + "\n"
        + r#"{"reason":"compiler-message","message":{"message":"unused import: `std::fs`","code":{"code":"unused_imports","explanation":null},"level":"warning","spans":[{"file_name":"src\\lib.rs","line_start":3,"column_start":5,"line_end":3,"column_end":12,"is_primary":true}],"children":[],"rendered":"warning: unused import: `std::fs`"}}"#;

    let diagnostics = parse_cargo_json_lines("cargo-check", &output);

    assert_eq!(diagnostics.len(), 1);
    let diagnostic = &diagnostics[0];
    assert_eq!(diagnostic.id, "cargo-check:unused_imports");
    assert_eq!(diagnostic.source, "cargo-check");
    assert_eq!(diagnostic.severity, DxSeverity::Warning);
    assert_eq!(diagnostic.file.as_deref(), Some("src\\lib.rs"));
    assert_eq!(diagnostic.line, Some(3));
    assert_eq!(diagnostic.column, Some(5));
    assert_eq!(diagnostic.message, "unused import: `std::fs`");
    assert_eq!(diagnostic.measurement, DxMeasurementKind::Measured);
    assert!(diagnostic.next_action.contains("Fix the Rust diagnostic"));
}

#[test]
fn parses_tool_output_from_plan_parser() {
    let plan = plan("rust-clippy", "cargo-json", DxToolTarget::Lint);
    let stderr = r#"{"reason":"compiler-message","message":{"message":"expected item","code":null,"level":"error","spans":[{"file_name":"src/main.rs","line_start":1,"column_start":1,"is_primary":true}]}}"#;

    let diagnostics = parse_tool_output(&plan, b"", stderr.as_bytes());

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "rust-clippy:error");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert_eq!(diagnostics[0].file.as_deref(), Some("src/main.rs"));
}

#[test]
fn parses_ruff_json_diagnostics() {
    let plan = plan("ruff-check", "ruff-json", DxToolTarget::Lint);
    let stdout = r#"[{"code":"F401","filename":"pkg/demo.py","message":"`os` imported but unused","location":{"row":2,"column":8}}]"#;

    let diagnostics = parse_tool_output(&plan, stdout.as_bytes(), b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "ruff-check:F401");
    assert_eq!(diagnostics[0].source, "ruff-check");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert_eq!(diagnostics[0].file.as_deref(), Some("pkg/demo.py"));
    assert_eq!(diagnostics[0].line, Some(2));
    assert_eq!(diagnostics[0].column, Some(8));
    assert!(diagnostics[0].message.contains("imported but unused"));
}

#[test]
fn parses_biome_json_diagnostics() {
    let plan = plan("biome-lint", "biome-json", DxToolTarget::Lint);
    let stdout = br#"{
  "summary": {
    "errors": 1,
    "warnings": 1
  },
  "diagnostics": [
    {
      "severity": "warning",
      "message": "This import is unused.",
      "category": "lint/correctness/noUnusedImports",
      "location": {
        "path": "src/app.ts",
        "start": { "line": 1, "column": 8 },
        "end": { "line": 1, "column": 12 }
      },
      "advices": []
    },
    {
      "severity": "error",
      "message": "Using == may be unsafe if you are relying on type coercion.",
      "category": "lint/suspicious/noDoubleEquals",
      "location": {
        "path": "src/app.ts",
        "start": { "line": 4, "column": 3 },
        "end": { "line": 4, "column": 5 }
      },
      "advices": []
    }
  ],
  "command": "lint"
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 2);
    assert_eq!(
        diagnostics[0].id,
        "biome-lint:lint/correctness/noUnusedImports"
    );
    assert_eq!(diagnostics[0].severity, DxSeverity::Warning);
    assert_eq!(diagnostics[0].file.as_deref(), Some("src/app.ts"));
    assert_eq!(diagnostics[0].line, Some(1));
    assert_eq!(diagnostics[0].column, Some(8));
    assert_eq!(
        diagnostics[1].id,
        "biome-lint:lint/suspicious/noDoubleEquals"
    );
    assert_eq!(diagnostics[1].severity, DxSeverity::Failure);
}

#[test]
fn parses_biome_json_after_experimental_reporter_warning() {
    let plan = plan("biome-format", "biome-json", DxToolTarget::Format);
    let stdout = br#"The --json option is unstable/experimental and its output might change between patches/minor releases.
{
  "summary": {
    "errors": 1,
    "warnings": 0
  },
  "diagnostics": [
    {
      "severity": "error",
      "message": "Formatter would have printed the following content:",
      "category": "format",
      "location": {
        "path": "src/app.ts",
        "start": { "line": 0, "column": 0 },
        "end": { "line": 0, "column": 0 }
      },
      "advices": []
    }
  ],
  "command": "format"
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "biome-format:format");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert_eq!(diagnostics[0].file.as_deref(), Some("src/app.ts"));
    assert!(diagnostics[0].next_action.contains("Biome formatter"));
}

#[test]
fn parses_biome_json_when_stderr_has_braced_warning_after_stdout() {
    let plan = plan("biome-lint", "biome-json", DxToolTarget::Lint);
    let stdout = br#"{
  "diagnostics": [
    {
      "severity": "warning",
      "message": "This import is unused.",
      "category": "lint/correctness/noUnusedImports"
    }
  ],
  "command": "lint"
}"#;
    let stderr = br#"warning: {experimental reporter output}"#;

    let diagnostics = parse_tool_output(&plan, stdout, stderr);

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(
        diagnostics[0].id,
        "biome-lint:lint/correctness/noUnusedImports"
    );
    assert_eq!(diagnostics[0].severity, DxSeverity::Warning);
}

#[test]
fn parses_biome_json_with_multiple_json_objects_uses_object_with_diagnostics() {
    let plan = plan("biome-lint", "biome-json", DxToolTarget::Lint);
    let stdout = br#"{"note":"Biome reporter prelude"}
{
  "diagnostics": [
    {
      "severity": "error",
      "message": "This is an unexpected use of the debugger statement.",
      "category": "lint/suspicious/noDebugger"
    }
  ],
  "command": "lint"
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "biome-lint:lint/suspicious/noDebugger");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
}

#[test]
fn invalid_biome_json_emits_invalid_runner_output_diagnostic() {
    let plan = plan("biome-lint", "biome-json", DxToolTarget::Lint);

    let diagnostics = parse_tool_output(&plan, b"not json", b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "biome-lint:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("biome-json"));
}

#[test]
fn parses_ruff_format_would_reformat_lines() {
    let plan = plan("ruff-format-check", "ruff-format", DxToolTarget::Format);

    let diagnostics = parse_tool_output(&plan, b"Would reformat: pkg/demo.py\n", b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "ruff-format-check:format");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert_eq!(diagnostics[0].file.as_deref(), Some("pkg/demo.py"));
}

#[test]
fn parses_black_check_output() {
    let plan = plan("black-format-check", "black", DxToolTarget::Format);
    let diagnostics = parse_tool_output(
        &plan,
        b"",
        b"would reformat app/main.py\nwould reformat tests/test_app.py\n2 files would be reformatted\n",
    );

    assert_eq!(diagnostics.len(), 2);
    assert_eq!(diagnostics[0].id, "black-format-check:format");
    assert_eq!(diagnostics[0].file.as_deref(), Some("app/main.py"));
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].next_action.contains("Black"));
    assert_eq!(diagnostics[1].file.as_deref(), Some("tests/test_app.py"));
}

#[test]
fn parses_go_line_oriented_outputs() {
    let gofmt = plan("gofmt-check", "gofmt-list", DxToolTarget::Format);
    let vet = plan("go-vet", "go-vet", DxToolTarget::Lint);
    let test = plan("go-test", "go-test", DxToolTarget::Test);

    let gofmt_diagnostics = parse_tool_output(&gofmt, b"main.go\ninternal/pkg/foo.go\n", b"");
    assert_eq!(gofmt_diagnostics.len(), 2);
    assert_eq!(gofmt_diagnostics[0].file.as_deref(), Some("main.go"));

    let vet_diagnostics = parse_tool_output(
        &vet,
        b"",
        b"./main.go:10:2: fmt.Println arg list ends with redundant newline\n",
    );
    assert_eq!(vet_diagnostics.len(), 1);
    assert_eq!(vet_diagnostics[0].file.as_deref(), Some("./main.go"));
    assert_eq!(vet_diagnostics[0].line, Some(10));
    assert_eq!(vet_diagnostics[0].column, Some(2));

    let test_diagnostics =
        parse_tool_output(&test, b"    thing_test.go:12: expected true\nFAIL\n", b"");
    assert_eq!(test_diagnostics.len(), 1);
    assert_eq!(test_diagnostics[0].file.as_deref(), Some("thing_test.go"));
    assert_eq!(test_diagnostics[0].line, Some(12));
}

#[test]
fn parses_rustfmt_check_output() {
    let plan = plan("rustfmt-check", "rustfmt", DxToolTarget::Format);

    let diagnostics = parse_tool_output(
        &plan,
        b"",
        b"Diff in src/lib.rs:1:\n- fn main(){}\n+ fn main() {}\n",
    );

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "rustfmt-check:format");
    assert_eq!(diagnostics[0].source, "rustfmt-check");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert_eq!(diagnostics[0].file.as_deref(), Some("src/lib.rs"));
    assert_eq!(diagnostics[0].line, Some(1));
    assert!(diagnostics[0].message.contains("rustfmt"));
}

#[test]
fn parses_package_script_typescript_diagnostics() {
    let plan = plan("js-typecheck", "package-script", DxToolTarget::Typecheck);

    let diagnostics = parse_tool_output(
        &plan,
        b"src/app.ts(12,5): error TS2322: Type 'string' is not assignable to type 'number'.\n",
        b"",
    );

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "js-typecheck:TS2322");
    assert_eq!(diagnostics[0].source, "js-typecheck");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert_eq!(diagnostics[0].file.as_deref(), Some("src/app.ts"));
    assert_eq!(diagnostics[0].line, Some(12));
    assert_eq!(diagnostics[0].column, Some(5));
    assert!(diagnostics[0].message.contains("not assignable"));
}

#[test]
fn parses_pytest_failed_tests() {
    let plan = plan("pytest", "pytest", DxToolTarget::Test);

    let diagnostics = parse_tool_output(
        &plan,
        b"tests/test_demo.py::test_demo FAILED                              [100%]\n",
        b"",
    );

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "pytest:test-failed");
    assert_eq!(diagnostics[0].source, "pytest");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert_eq!(diagnostics[0].file.as_deref(), Some("tests/test_demo.py"));
    assert!(diagnostics[0].message.contains("test_demo"));
}

#[test]
fn invalid_ruff_json_emits_invalid_runner_output_diagnostic() {
    let plan = plan("ruff-check", "ruff-json", DxToolTarget::Lint);

    let diagnostics = parse_tool_output(&plan, b"not json", b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "ruff-check:runner-output-invalid");
    assert_eq!(diagnostics[0].source, "ruff-check");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].file.is_none());
    assert!(diagnostics[0].message.contains("machine-readable"));
    assert!(diagnostics[0].message.contains("not json"));
}

#[test]
fn malformed_cargo_compiler_message_emits_invalid_runner_output_diagnostic() {
    let plan = plan("cargo-check", "cargo-json", DxToolTarget::Typecheck);
    let stdout = br#"{"reason":"compiler-message","message":{"level":"error","spans":[]}}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "cargo-check:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("message"));
}

#[test]
fn malformed_ruff_json_item_emits_invalid_runner_output_diagnostic() {
    let plan = plan("ruff-check", "ruff-json", DxToolTarget::Lint);
    let stdout = br#"[{"code":"F401","filename":"pkg/demo.py","location":{"row":2,"column":8}}]"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "ruff-check:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("message"));
}

#[test]
fn malformed_biome_json_item_emits_invalid_runner_output_diagnostic() {
    let plan = plan("biome-lint", "biome-json", DxToolTarget::Lint);
    let stdout = br#"{"diagnostics":[{"severity":"error","category":"lint/suspicious/noDebugger"}],"command":"lint"}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "biome-lint:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("message"));
}

#[test]
fn malformed_web_audit_json_item_emits_invalid_runner_output_diagnostic() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{"url":"http://localhost:3000/","diagnostics":[{"id":"web-http-status","severity":"failure"}]}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("diagnostics"));
}

#[test]
fn malformed_biome_diagnostics_shape_fails_before_later_valid_report() {
    let plan = plan("biome-lint", "biome-json", DxToolTarget::Lint);
    let stdout = br#"{"diagnostics":"not-an-array"}
{"diagnostics":[{"severity":"warning","message":"Unused import.","category":"lint/correctness/noUnusedImports"}],"command":"lint"}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "biome-lint:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("diagnostics array"));
}

#[test]
fn blank_required_structured_messages_emit_invalid_runner_output() {
    let cases = [
        (
            "cargo-check",
            "cargo-json",
            DxToolTarget::Typecheck,
            br#"{"reason":"compiler-message","message":{"message":"","level":"error","spans":[]}}"#.as_slice(),
        ),
        (
            "ruff-check",
            "ruff-json",
            DxToolTarget::Lint,
            br#"[{"code":"F401","message":"","filename":"pkg/demo.py","location":{"row":2,"column":8}}]"#.as_slice(),
        ),
        (
            "biome-lint",
            "biome-json",
            DxToolTarget::Lint,
            br#"{"diagnostics":[{"severity":"error","message":"","category":"lint/suspicious/noDebugger"}],"command":"lint"}"#.as_slice(),
        ),
    ];

    for (id, parser, target, stdout) in cases {
        let plan = plan(id, parser, target);
        let diagnostics = parse_tool_output(&plan, stdout, b"");

        assert_eq!(diagnostics.len(), 1, "{id}");
        assert_eq!(diagnostics[0].id, format!("{id}:runner-output-invalid"));
        assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
        assert!(
            diagnostics[0].message.contains("message"),
            "{id} should explain the missing message text: {:?}",
            diagnostics[0].message
        );
    }
}

#[test]
fn malformed_web_audit_diagnostics_shape_emits_invalid_runner_output() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{"url":"http://localhost:3000/","diagnostics":{"id":"web-http-status"}}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("diagnostics"));
}

#[test]
fn malformed_web_lighthouse_audit_item_emits_invalid_runner_output() {
    let plan = plan("web-audit-home", "web-audit-json", DxToolTarget::Audit);
    let stdout = br#"{
  "url": "http://localhost:3000/",
  "diagnostics": [],
  "lighthouse": {
    "audits": [
      {
        "id": "performance-http-status",
        "status": "blocked",
        "detail": "Returned HTTP 503",
        "next_action": "Fix the route."
      }
    ]
  }
}"#;

    let diagnostics = parse_tool_output(&plan, stdout, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "web-audit-home:runner-output-invalid");
    assert_eq!(diagnostics[0].severity, DxSeverity::Failure);
    assert!(diagnostics[0].message.contains("lighthouse audit"));
}

#[test]
fn non_array_ruff_json_emits_invalid_runner_output_diagnostic() {
    let plan = plan("ruff-check", "ruff-json", DxToolTarget::Lint);

    let diagnostics = parse_tool_output(&plan, br#"{"message":"wrong shape"}"#, b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "ruff-check:runner-output-invalid");
    assert!(diagnostics[0].message.contains("expected JSON array"));
}

#[test]
fn malformed_cargo_json_lines_emit_invalid_runner_output_diagnostic() {
    let plan = plan("cargo-check", "cargo-json", DxToolTarget::Typecheck);
    let stdout = "not json\n{\"reason\":\"compiler-artifact\"}\n";

    let diagnostics = parse_tool_output(&plan, stdout.as_bytes(), b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "cargo-check:runner-output-invalid");
    assert!(diagnostics[0].message.contains("not json"));
}

#[test]
fn cargo_json_ignores_valid_non_diagnostic_messages() {
    let plan = plan("cargo-check", "cargo-json", DxToolTarget::Typecheck);

    let diagnostics = parse_tool_output(
        &plan,
        br#"{"reason":"compiler-artifact","package_id":"demo 0.1.0"}"#,
        b"",
    );

    assert!(diagnostics.is_empty());
}

#[test]
fn multiple_malformed_cargo_json_lines_emit_one_invalid_runner_output_diagnostic() {
    let plan = plan("cargo-check", "cargo-json", DxToolTarget::Typecheck);
    let stdout = "not json\nalso not json\n{\"reason\":\"compiler-artifact\"}\n";

    let diagnostics = parse_tool_output(&plan, stdout.as_bytes(), b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "cargo-check:runner-output-invalid");
    assert!(diagnostics[0].message.contains("not json"));
    assert!(!diagnostics[0].message.contains("also not json"));
}

#[test]
fn unknown_parser_with_output_emits_invalid_runner_output_diagnostic() {
    let plan = plan("custom-runner", "typo-parser", DxToolTarget::Lint);

    let diagnostics = parse_tool_output(&plan, b"unexpected tool output", b"");

    assert_eq!(diagnostics.len(), 1);
    assert_eq!(diagnostics[0].id, "custom-runner:runner-output-invalid");
    assert!(diagnostics[0].message.contains("unknown parser"));
}
